max_width = 79
fn_brace_style = "PreferSameLine"
trailing_comma = "Vertical"
fn_return_indent = "WithWhereClause"
fn_args_paren_newline = true
fn_args_density = "Compressed"
fn_args_layout = "Visual"
where_density = "Compressed"
where_layout = "Mixed"
fn_call_style = "Visual"
chain_indent = "Visual"
reorder_imports_in_groups = false
reorder_imported_names = true
single_line_if_else_max_width = 0
format_strings = true
hard_tabs = true
wrap_comments = true
normalize_comments = true
use_try_shorthand = true
write_mode = "Overwrite"
condense_wildcard_suffixes = true
combine_control_expr = false
